stages:
  train:
    cmd: python YOLOX/train.py -f YOLOX/exps/example/custom/yolox_s.py -d 1 -b 8 --fp16 -o -c yolox_s.pth
    deps:
    - YOLOX/train.py
    - YOLOX/exps/example/custom/yolox_s.py
    outs:
    - YOLOX/YOLOX_outputs/yolox_x/best_ckpt.pth 
  infer:
    cmd: python YOLOX/tools/demo.py image -n yolox-s -c YOLOX/weights/yolox_s.pth \
            --path YOLOX/assets/dog.jpg \
            --save_result --conf 0.25 --device cpu
    deps:
      - YOLOX/tools/demo.py
      - YOLOX/weights/yolox_s.pth
      - YOLOX/assets/dog.jpg
    outs:
      - infer_outputs/dog.jpg
